export { TemplatesPage } from './pages/TemplatesPage';
export {
  useActivateTemplate,
  useActiveTemplates,
  useConfirmActivateTemplate,
  templateQueryKeys,
  useCreateTemplate,
  useDeleteTemplate,
  useDuplicateTemplate,
  useDeactivateTemplate,
  useTemplateAssignableUsers,
  useTemplateDefaults,
  useTemplateCreators,
  useTemplateDetail,
  useTemplates,
  useUpdateTemplate,
} from './hooks/useTemplateData';
export type {
  IssueTemplate,
  TemplateApplyDraft,
  TemplateActivationConflictDetails,
  TemplateActivationResult,
  TemplateAssigneeType,
  TemplateCategory,
  TemplateCreator,
  TemplateDefaultsResponse,
  TemplateDraftInput,
  TemplateListInput,
  TemplateSort,
} from './types';
